Improve docker file for android build.

diff --git a/docker/Dockerfile-android b/docker/Dockerfile-android
--- a/docker/Dockerfile-android
+++ b/docker/Dockerfile-android
@@ -11,8 +11,18 @@ ENV ANDROID_NDK_ROOT=/android/android-ndk-r18b \
     JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 \
     QT5_ANDROID=/android/Qt/5.12.0/ \
     ANDROID_ABI=armeabi-v7a \
-    QT_ARCH=armv7 \
-    QT5_ANDROID_CMAKE=${QT5_ANDROID}/android_${QT_ARCH}/lib/cmake
+    QT_ARCH=armv7
+
+# re-using variables seems only to work properly if they are set in different ENV commands
+ENV QT5_ANDROID_CMAKE=${QT5_ANDROID}/android_${QT_ARCH}/lib/cmake
+
+# Check that all environment variables point to existing directories
+# TODO: implement a script for that with colored warnings (use "tput" to color the warnings)
+RUN if [ ! -d ${ANDROID_NDK_ROOT} ] ; then tput echo "Android NDK not found in ANDROID_NDK_ROOT = " ${ANDROID_NDK_ROOT} ; exit 1 ; fi ; \
+    if [ ! -d ${ANDROID_SDK_ROOT} ] ; then echo "Android SDK not found in ANDROID_SDK_ROOT = " ${ANDROID_SDK_ROOT} ; exit 1 ; fi ; \
+    if [ ! -d ${JAVA_HOME} ] ; then echo "Java not found in JAVA_HOME = " ${JAVA_HOME} ; exit 1 ; fi ; \
+    if [ ! -d ${QT5_ANDROID} ] ; then echo "Qt5 Android not found in QT5_ANDROID = " ${QT5_ANDROID} ; exit 1 ; fi ; \
+    if [ ! -e ${QT5_ANDROID_CMAKE} ] ; then echo "Qt5 Android cmake file not found in QT5_ANDROID_CMAKE = " ${QT5_ANDROID_CMAKE} ; exit 1 ; fi
 
 RUN apt-get update && apt-get install -y eatmydata auto-apt-proxy
 
@@ -27,6 +37,9 @@ RUN cd $ANDROID_SDK_ROOT/tools/bin/ \
 RUN mkdir -p /src/build && mkdir -p /build
 ADD . src/qhanoi
 
+# Note: We normally expect to be able to simply specify the Qt5 path in CMAKE_PREFIX_PATH, but then some
+# modules are not found (according to online search, maybe a bug in Ubuntu 18.04). Therefore, we specify
+# the directories for each module.
 RUN cd /build && \
     eatmydata cmake -DCMAKE_SYSTEM_NAME="Android" \
         -DANDROID_ABI=$ANDROID_ABI \
@@ -41,5 +54,11 @@ RUN cd /build && \
         -DQt5Core_DIR=${QT5_ANDROID}/android_armv7/lib/cmake/Qt5Core -DQt5Xml_DIR=${QT5_ANDROID}/android_armv7/lib/cmake/Qt5Xml \
         -DQt5Widgets_DIR=${QT5_ANDROID}/android_armv7/lib/cmake/Qt5Widgets/ -DCMAKE_PREFIX_PATH=QT5_ANDROID/android_armv7/lib \
         /src/qhanoi
-        
-RUN cd /build && cmake --build . -- VERBOSE=1
+
+# This runs make from the Android NDK.
+# TODO: add -j x to use more CPUs.
+RUN cd /build && eatmydata cmake --build . -- VERBOSE=1
+
+# APK to be found in: /build/src//build/outputs/apk/debug/src-debug.apk
+
+# TODO: the resulting APK file is signed, but by whom?
