Fix detection of required directories.
Missing quotation marks around variable names caused "-d" to not work properly.

diff --git a/docker/Dockerfile-android b/docker/Dockerfile-android
--- a/docker/Dockerfile-android
+++ b/docker/Dockerfile-android
@@ -29,11 +29,12 @@ ENV QT5_ANDROID_CMAKE=${QT5_ANDROID}/android_${QT_ARCH}/lib/cmake
 
 # Check that all environment variables point to existing directories
 # TODO: implement a script for that with colored warnings (use "tput" to color the warnings)
-RUN if [ ! -d ${ANDROID_NDK_ROOT} ] ; then tput echo "Android NDK not found in ANDROID_NDK_ROOT = " ${ANDROID_NDK_ROOT} ; exit 1 ; fi ; \
-    if [ ! -d ${ANDROID_SDK_ROOT} ] ; then echo "Android SDK not found in ANDROID_SDK_ROOT = " ${ANDROID_SDK_ROOT} ; exit 1 ; fi ; \
-    if [ ! -d ${JAVA_HOME} ] ; then echo "Java not found in JAVA_HOME = " ${JAVA_HOME} ; exit 1 ; fi ; \
-    if [ ! -d ${QT5_ANDROID} ] ; then echo "Qt5 Android not found in QT5_ANDROID = " ${QT5_ANDROID} ; exit 1 ; fi ; \
-    if [ ! -e ${QT5_ANDROID_CMAKE} ] ; then echo "Qt5 Android cmake file not found in QT5_ANDROID_CMAKE = " ${QT5_ANDROID_CMAKE} ; exit 1 ; fi
+# Note that [ ! -d requires its filepath to be in quotes, otherwise it does not report missing directories!
+RUN if [ ! -d "${ANDROID_NDK_ROOT}" ] ; then echo "Android NDK not found in ANDROID_NDK_ROOT = " ${ANDROID_NDK_ROOT} ; exit 1 ; fi ; \
+    if [ ! -d "${ANDROID_SDK_ROOT}" ] ; then echo "Android SDK not found in ANDROID_SDK_ROOT = " ${ANDROID_SDK_ROOT} ; exit 1 ; fi ; \
+    if [ ! -d "${JAVA_HOME}" ] ; then echo "Java not found in JAVA_HOME = " ${JAVA_HOME} ; exit 1 ; fi ; \
+    if [ ! -d "${QT5_ANDROID}" ] ; then echo "Qt5 Android not found in QT5_ANDROID = " ${QT5_ANDROID} ; exit 1 ; fi ; \
+    if [ ! -e "${QT5_ANDROID_CMAKE}" ] ; then echo "Qt5 Android cmake file not found in QT5_ANDROID_CMAKE = " ${QT5_ANDROID_CMAKE} ; exit 1 ; fi
 
 # Only install these packages if not yet installed. This saves the "apt-get update".
 RUN if \
